[package]
name = "optd-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bitvec = "1.0.1"
itertools = "0.14.0"
pretty-xmlish = "0.1.13"
tokio = { version = "1.47.0", features = [
    "rt-multi-thread",
    "sync",
    "macros",
    "parking_lot",
] }
tracing = "0.1.41"
tracing-test = "0.2.5"
