[package]
name = "optd-catalog"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
datafusion = "=49.0.0"
sqlx = { version = "=0.8.6", features = ["sqlite"] }
parking_lot = "=0.12.4"
glob = "0.3.2"
url = "2.5.4"
async-trait = "0.1.88"
tokio = { workspace = true, features = ["full"] }

[dependencies.uuid]
version = "1.17.0"
# Lets you generate random UUIDs
features = ["v4"]
