[package]
name = "optd-datafusion"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
datafusion = { workspace = true }
tracing = { workspace = true, features = ["log"] }
optd-core = { path = "../../optd/core", version = "0.1" }
